import type { Background } from "@/lib/rules/types";

export const BACKGROUNDS: Background[] = [
  {
    id: "acolyte",
    name: "Acolyte",
    abilityScores: ["int", "wis", "cha"],
    skillProficiencies: ["insight", "religion"],
    toolProficiency: null,
    originFeatId: "magic_initiate",
    equipment: [
      { equipmentId: "travelers_clothes", quantity: 1 },
      { equipmentId: "rations", quantity: 2 },
      { equipmentId: "backpack", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You spent your early years in service to a temple, learning rites and lore.",
  },
  {
    id: "criminal",
    name: "Criminal",
    abilityScores: ["dex", "con", "int"],
    skillProficiencies: ["sleight_of_hand", "stealth"],
    toolProficiency: "thieves_tools",
    originFeatId: "alert",
    equipment: [
      { equipmentId: "crowbar", quantity: 1 },
      { equipmentId: "rope_hempen", quantity: 1 },
      { equipmentId: "travelers_clothes", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You have a history of breaking the law and survived by wit and stealth.",
  },
  {
    id: "sage",
    name: "Sage",
    abilityScores: ["con", "int", "wis"],
    skillProficiencies: ["arcana", "history"],
    toolProficiency: null,
    originFeatId: "skilled",
    equipment: [
      { equipmentId: "rations", quantity: 3 },
      { equipmentId: "travelers_clothes", quantity: 1 },
      { equipmentId: "backpack", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You spent years learning the lore of the multiverse in libraries and archives.",
  },
  {
    id: "soldier",
    name: "Soldier",
    abilityScores: ["str", "dex", "con"],
    skillProficiencies: ["athletics", "intimidation"],
    toolProficiency: "playing_card_set",
    originFeatId: "savage_attacker",
    equipment: [
      { equipmentId: "spear", quantity: 1 },
      { equipmentId: "shortbow", quantity: 1 },
      { equipmentId: "healers_kit", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You fought in a militia, mercenary company, or standing army before adventuring.",
  },
  {
    id: "guide",
    name: "Guide",
    abilityScores: ["dex", "con", "wis"],
    skillProficiencies: ["stealth", "survival"],
    toolProficiency: null,
    originFeatId: "magic_initiate",
    equipment: [
      { equipmentId: "shortbow", quantity: 1 },
      { equipmentId: "rope_hempen", quantity: 1 },
      { equipmentId: "bedroll", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You grew up in the wilds, leading travelers safely across dangerous country.",
  },
  {
    id: "artisan",
    name: "Artisan",
    abilityScores: ["str", "dex", "int"],
    skillProficiencies: ["investigation", "persuasion"],
    toolProficiency: "smiths_tools",
    originFeatId: "crafter",
    equipment: [
      { equipmentId: "smiths_tools", quantity: 1 },
      { equipmentId: "backpack", quantity: 1 },
      { equipmentId: "travelers_clothes", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You apprenticed to a master craftsperson, learning a trade and its tools.",
  },
  {
    id: "entertainer",
    name: "Entertainer",
    abilityScores: ["str", "dex", "cha"],
    skillProficiencies: ["acrobatics", "performance"],
    toolProficiency: "instrument_lute",
    originFeatId: "musician",
    equipment: [
      { equipmentId: "disguise_kit", quantity: 1 },
      { equipmentId: "bedroll", quantity: 1 },
      { equipmentId: "rations", quantity: 3 },
    ],
    goldAlternative: 50,
    description: "You've spent your life on stage, delighting crowds with music, comedy, or story.",
  },
  {
    id: "noble",
    name: "Noble",
    abilityScores: ["str", "int", "cha"],
    skillProficiencies: ["history", "persuasion"],
    toolProficiency: "playing_card_set",
    originFeatId: "skilled",
    equipment: [
      { equipmentId: "rapier", quantity: 1 },
      { equipmentId: "playing_card_set", quantity: 1 },
      { equipmentId: "travelers_clothes", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You were raised in privilege as part of a family of wealth and influence.",
  },
  {
    id: "sailor",
    name: "Sailor",
    abilityScores: ["str", "dex", "wis"],
    skillProficiencies: ["acrobatics", "perception"],
    toolProficiency: "navigators_tools",
    originFeatId: "tavern_brawler",
    equipment: [
      { equipmentId: "dagger", quantity: 1 },
      { equipmentId: "rope_hempen", quantity: 1 },
      { equipmentId: "navigators_tools", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You've spent your life aboard ships, crossing oceans and braving storms.",
  },
  {
    id: "scribe",
    name: "Scribe",
    abilityScores: ["dex", "int", "wis"],
    skillProficiencies: ["investigation", "perception"],
    toolProficiency: "calligraphers_supplies",
    originFeatId: "skilled",
    equipment: [
      { equipmentId: "dagger", quantity: 1 },
      { equipmentId: "spellbook", quantity: 1 },
      { equipmentId: "backpack", quantity: 1 },
    ],
    goldAlternative: 50,
    description: "You worked as a copyist and record-keeper, prized for a precise hand.",
  },
];

export const BACKGROUND_BY_ID: Record<string, Background> = Object.fromEntries(
  BACKGROUNDS.map((b) => [b.id, b]),
);
