import type { ClassDef } from "@/lib/rules/types";

export const CLASSES: ClassDef[] = [
  {
    id: "barbarian",
    name: "Barbarian",
    hitDie: 12,
    primaryAbilities: ["str"],
    savingThrows: ["str", "con"],
    armorProficiencies: ["light", "medium", "shields"],
    weaponProficiencies: ["simple", "martial"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["animal_handling", "athletics", "intimidation", "nature", "perception", "survival"],
    startingEquipment: [
      { equipmentId: "greataxe", quantity: 1 },
      { equipmentId: "handaxe", quantity: 2 },
      { equipmentId: "javelin", quantity: 4 },
      { equipmentId: "explorers_pack", quantity: 1 },
    ],
    spellcastingAbility: null,
    spellcastingType: "none",
    cantripsKnownAtLevel1: 0,
    spellsPreparedOrKnownAtLevel1: 0,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Rage",
        description:
          "As a bonus action, enter a rage for 1 minute: advantage on Strength checks/saves, bonus melee damage, and resistance to bludgeoning, piercing, and slashing damage. Limited uses per Long Rest.",
      },
      {
        name: "Unarmored Defense",
        description:
          "While not wearing armor, your AC equals 10 + your Dexterity modifier + your Constitution modifier. You can still use a shield.",
      },
    ],
    description: "A fierce warrior who can enter a battle rage, drawing on primal fury.",
  },
  {
    id: "bard",
    name: "Bard",
    hitDie: 8,
    primaryAbilities: ["cha"],
    savingThrows: ["dex", "cha"],
    armorProficiencies: ["light"],
    weaponProficiencies: ["simple", "hand_crossbow", "longsword", "rapier", "shortsword"],
    toolProficiencies: ["musical_instrument_x3"],
    skillChoiceCount: 3,
    skillChoices: [
      "acrobatics", "animal_handling", "arcana", "athletics", "deception", "history",
      "insight", "intimidation", "investigation", "medicine", "nature", "perception",
      "performance", "persuasion", "religion", "sleight_of_hand", "stealth", "survival",
    ],
    startingEquipment: [
      { equipmentId: "rapier", quantity: 1 },
      { equipmentId: "leather", quantity: 1 },
      { equipmentId: "dagger", quantity: 1 },
      { equipmentId: "instrument_lute", quantity: 1 },
      { equipmentId: "diplomats_pack", quantity: 1 },
    ],
    spellcastingAbility: "cha",
    spellcastingType: "known",
    cantripsKnownAtLevel1: 2,
    spellsPreparedOrKnownAtLevel1: 4,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Bardic Inspiration",
        description:
          "As a bonus action, give a creature within 60 feet a Bardic Inspiration die (d6). They can add it to one ability check, attack roll, or saving throw. Uses = Charisma modifier per Long Rest.",
      },
      {
        name: "Spellcasting",
        description: "You know a number of Bard spells, cast using Charisma.",
      },
    ],
    description: "A master of song, speech, and the magic they contain, who can inspire allies and cast varied spells.",
  },
  {
    id: "cleric",
    name: "Cleric",
    hitDie: 8,
    primaryAbilities: ["wis"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["light", "medium", "shields"],
    weaponProficiencies: ["simple"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["history", "insight", "medicine", "persuasion", "religion"],
    startingEquipment: [
      { equipmentId: "mace", quantity: 1 },
      { equipmentId: "scale_mail", quantity: 1 },
      { equipmentId: "shield", quantity: 1 },
      { equipmentId: "holy_symbol", quantity: 1 },
      { equipmentId: "priests_pack", quantity: 1 },
    ],
    spellcastingAbility: "wis",
    spellcastingType: "prepared",
    cantripsKnownAtLevel1: 3,
    spellsPreparedOrKnownAtLevel1: "ability_plus_level",
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Spellcasting",
        description: "You prepare a number of Cleric spells each day, cast using Wisdom.",
      },
      {
        name: "Divine Order",
        description:
          "Choose Protector (proficiency with martial weapons and heavy armor) or Thaumaturge (an extra cantrip and a bonus to certain Religion/Arcana checks).",
      },
    ],
    description: "A priestly champion who wields divine magic in service of a deity or cause.",
  },
  {
    id: "druid",
    name: "Druid",
    hitDie: 8,
    primaryAbilities: ["wis"],
    savingThrows: ["int", "wis"],
    armorProficiencies: ["light", "medium", "shields"],
    weaponProficiencies: ["club", "dagger", "dart", "javelin", "mace", "quarterstaff", "scimitar", "sickle", "sling", "spear"],
    toolProficiencies: ["herbalism_kit"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "animal_handling", "insight", "medicine", "nature", "perception", "religion", "survival"],
    startingEquipment: [
      { equipmentId: "sickle", quantity: 1 },
      { equipmentId: "leather", quantity: 1 },
      { equipmentId: "herbalism_kit", quantity: 1 },
      { equipmentId: "druidic_focus_sprig", quantity: 1 },
      { equipmentId: "explorers_pack", quantity: 1 },
    ],
    spellcastingAbility: "wis",
    spellcastingType: "prepared",
    cantripsKnownAtLevel1: 2,
    spellsPreparedOrKnownAtLevel1: "ability_plus_level",
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Spellcasting",
        description: "You prepare a number of Druid spells each day, cast using Wisdom.",
      },
      {
        name: "Druidic",
        description: "You know Druidic, the secret language of druids.",
      },
    ],
    description: "A priest of the Old Faith, wielding the powers of nature and adopting animal forms.",
  },
  {
    id: "fighter",
    name: "Fighter",
    hitDie: 10,
    primaryAbilities: ["str", "dex"],
    savingThrows: ["str", "con"],
    armorProficiencies: ["light", "medium", "heavy", "shields"],
    weaponProficiencies: ["simple", "martial"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["acrobatics", "animal_handling", "athletics", "history", "insight", "intimidation", "perception", "survival"],
    startingEquipment: [
      { equipmentId: "chain_mail", quantity: 1 },
      { equipmentId: "longsword", quantity: 1 },
      { equipmentId: "shield", quantity: 1 },
      { equipmentId: "explorers_pack", quantity: 1 },
      { equipmentId: "handaxe", quantity: 2 },
    ],
    spellcastingAbility: null,
    spellcastingType: "none",
    cantripsKnownAtLevel1: 0,
    spellsPreparedOrKnownAtLevel1: 0,
    hasFightingStyleAtLevel1: true,
    extraAsiLevels: [6, 14],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Fighting Style",
        description: "Choose a Fighting Style feat (Archery, Defense, Dueling, Great Weapon Fighting, Protection, or Two-Weapon Fighting).",
      },
      {
        name: "Second Wind",
        description: "As a bonus action, regain 1d10 + your Fighter level in hit points. Limited uses per rest.",
      },
    ],
    description: "A master of martial combat, skilled with a variety of weapons and armor.",
  },
  {
    id: "monk",
    name: "Monk",
    hitDie: 8,
    primaryAbilities: ["dex", "wis"],
    savingThrows: ["str", "dex"],
    armorProficiencies: [],
    weaponProficiencies: ["simple", "shortsword"],
    toolProficiencies: ["artisan_or_instrument_x1"],
    skillChoiceCount: 2,
    skillChoices: ["acrobatics", "athletics", "history", "insight", "religion", "stealth"],
    startingEquipment: [
      { equipmentId: "shortsword", quantity: 1 },
      { equipmentId: "dart", quantity: 10 },
      { equipmentId: "explorers_pack", quantity: 1 },
    ],
    spellcastingAbility: null,
    spellcastingType: "none",
    cantripsKnownAtLevel1: 0,
    spellsPreparedOrKnownAtLevel1: 0,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Martial Arts",
        description: "Use Dexterity for unarmed strikes and monk weapons; unarmed strikes deal 1d6; can make a bonus-action unarmed strike.",
      },
      {
        name: "Unarmored Defense",
        description: "While not wearing armor or a shield, your AC equals 10 + Dexterity modifier + Wisdom modifier.",
      },
    ],
    description: "A master of martial arts who channels inner power (ki) through disciplined training.",
  },
  {
    id: "paladin",
    name: "Paladin",
    hitDie: 10,
    primaryAbilities: ["str", "cha"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["light", "medium", "heavy", "shields"],
    weaponProficiencies: ["simple", "martial"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"],
    startingEquipment: [
      { equipmentId: "chain_mail", quantity: 1 },
      { equipmentId: "longsword", quantity: 1 },
      { equipmentId: "shield", quantity: 1 },
      { equipmentId: "javelin", quantity: 5 },
      { equipmentId: "priests_pack", quantity: 1 },
    ],
    spellcastingAbility: "cha",
    spellcastingType: "prepared",
    cantripsKnownAtLevel1: 0,
    spellsPreparedOrKnownAtLevel1: 0,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Lay on Hands",
        description: "A pool of healing power equal to 5 × your Paladin level; spend points to heal HP or cure a disease/poison as an action.",
      },
      {
        name: "Divine Sense",
        description: "As an action, detect the presence of celestials, fiends, and undead within 60 feet. Limited uses per Long Rest.",
      },
    ],
    description: "A holy warrior bound by a sacred oath to stand against the forces of evil.",
  },
  {
    id: "ranger",
    name: "Ranger",
    hitDie: 10,
    primaryAbilities: ["dex", "wis"],
    savingThrows: ["str", "dex"],
    armorProficiencies: ["light", "medium", "shields"],
    weaponProficiencies: ["simple", "martial"],
    toolProficiencies: [],
    skillChoiceCount: 3,
    skillChoices: ["animal_handling", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"],
    startingEquipment: [
      { equipmentId: "leather", quantity: 1 },
      { equipmentId: "shortsword", quantity: 2 },
      { equipmentId: "longbow", quantity: 1 },
      { equipmentId: "explorers_pack", quantity: 1 },
    ],
    spellcastingAbility: "wis",
    spellcastingType: "known",
    cantripsKnownAtLevel1: 0,
    spellsPreparedOrKnownAtLevel1: 0,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Favored Enemy",
        description: "Choose a type of enemy you know well; gain benefits tracking, recalling knowledge of, and communicating about creatures of that type.",
      },
      {
        name: "Deft Explorer",
        description: "Gain an Expertise skill and other exploration benefits.",
      },
    ],
    description: "A warrior who uses martial prowess and nature magic to protect the wild places and hunt down foes.",
  },
  {
    id: "rogue",
    name: "Rogue",
    hitDie: 8,
    primaryAbilities: ["dex"],
    savingThrows: ["dex", "int"],
    armorProficiencies: ["light"],
    weaponProficiencies: ["simple", "hand_crossbow", "longsword", "rapier", "shortsword"],
    toolProficiencies: ["thieves_tools"],
    skillChoiceCount: 4,
    skillChoices: [
      "acrobatics", "athletics", "deception", "insight", "intimidation", "investigation",
      "perception", "performance", "persuasion", "sleight_of_hand", "stealth",
    ],
    startingEquipment: [
      { equipmentId: "rapier", quantity: 1 },
      { equipmentId: "shortbow", quantity: 1 },
      { equipmentId: "leather", quantity: 1 },
      { equipmentId: "thieves_tools", quantity: 1 },
      { equipmentId: "burglars_pack", quantity: 1 },
      { equipmentId: "dagger", quantity: 2 },
    ],
    spellcastingAbility: null,
    spellcastingType: "none",
    cantripsKnownAtLevel1: 0,
    spellsPreparedOrKnownAtLevel1: 0,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Expertise",
        description: "Choose two skill proficiencies (or one skill and thieves' tools); your proficiency bonus is doubled for checks with them.",
      },
      {
        name: "Sneak Attack",
        description: "Once per turn, deal extra damage (1d6 at level 1) to a creature you hit with advantage or that has another enemy within 5 feet of it.",
      },
      {
        name: "Thieves' Cant",
        description: "You know Thieves' Cant, a secret mix of dialect, jargon, and code.",
      },
    ],
    description: "A scoundrel who uses stealth and trickery to overcome obstacles and enemies alike.",
  },
  {
    id: "sorcerer",
    name: "Sorcerer",
    hitDie: 6,
    primaryAbilities: ["cha"],
    savingThrows: ["con", "cha"],
    armorProficiencies: [],
    weaponProficiencies: ["dagger", "dart", "sling", "quarterstaff", "light_crossbow"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"],
    startingEquipment: [
      { equipmentId: "light_crossbow", quantity: 1 },
      { equipmentId: "component_pouch", quantity: 1 },
      { equipmentId: "dagger", quantity: 2 },
      { equipmentId: "dungeoneers_pack", quantity: 1 },
    ],
    spellcastingAbility: "cha",
    spellcastingType: "known",
    cantripsKnownAtLevel1: 4,
    spellsPreparedOrKnownAtLevel1: 2,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Spellcasting",
        description: "You know a number of Sorcerer spells, cast using Charisma.",
      },
      {
        name: "Innate Sorcery",
        description: "As a bonus action, surge with power for a minute: advantage on spell attack rolls and +1 to spell save DC. Limited uses per Long Rest.",
      },
    ],
    description: "A spellcaster who draws on inborn magic from a gift or bloodline.",
  },
  {
    id: "warlock",
    name: "Warlock",
    hitDie: 8,
    primaryAbilities: ["cha"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["light"],
    weaponProficiencies: ["simple"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"],
    startingEquipment: [
      { equipmentId: "leather", quantity: 1 },
      { equipmentId: "dagger", quantity: 2 },
      { equipmentId: "component_pouch", quantity: 1 },
      { equipmentId: "scholars_pack", quantity: 1 },
    ],
    spellcastingAbility: "cha",
    spellcastingType: "pact",
    cantripsKnownAtLevel1: 2,
    spellsPreparedOrKnownAtLevel1: 2,
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 1,
    level1Features: [
      {
        name: "Pact Magic",
        description: "You know a number of Warlock spells, cast using Charisma from a small number of slots that always cast at your highest available level and recharge on a Short Rest.",
      },
      {
        name: "Otherworldly Patron",
        description: "Choose the patron that grants your power (chosen at level 1 for Warlocks, unlike other classes' later subclass choice).",
      },
    ],
    description: "A wielder of magic granted by a pact with an otherworldly patron.",
  },
  {
    id: "wizard",
    name: "Wizard",
    hitDie: 6,
    primaryAbilities: ["int"],
    savingThrows: ["int", "wis"],
    armorProficiencies: [],
    weaponProficiencies: ["dagger", "dart", "sling", "quarterstaff", "light_crossbow"],
    toolProficiencies: [],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "history", "insight", "investigation", "medicine", "religion"],
    startingEquipment: [
      { equipmentId: "quarterstaff", quantity: 1 },
      { equipmentId: "component_pouch", quantity: 1 },
      { equipmentId: "spellbook", quantity: 1 },
      { equipmentId: "scholars_pack", quantity: 1 },
    ],
    spellcastingAbility: "int",
    spellcastingType: "prepared",
    cantripsKnownAtLevel1: 3,
    spellsPreparedOrKnownAtLevel1: "ability_plus_level",
    hasFightingStyleAtLevel1: false,
    extraAsiLevels: [],
    subclassLevel: 3,
    level1Features: [
      {
        name: "Spellcasting",
        description: "You prepare a number of Wizard spells from your spellbook each day, cast using Intelligence.",
      },
      {
        name: "Ritual Adept",
        description: "You can cast any spell in your spellbook that has the ritual tag as a Ritual, without preparing it.",
      },
      {
        name: "Arcane Recovery",
        description: "Once per day when you finish a Short Rest, recover expended spell slots with a combined level up to half your Wizard level (rounded up).",
      },
    ],
    description: "A scholarly magic-user capable of manipulating the structures of spellcasting.",
  },
];

export const CLASS_BY_ID: Record<string, ClassDef> = Object.fromEntries(
  CLASSES.map((c) => [c.id, c]),
);
