import type { Monster } from "@/lib/rules/types";

export const MONSTERS: Monster[] = [
  {
    id: "goblin",
    name: "Goblin",
    size: "Small",
    type: "Fey",
    alignment: "Neutral Evil",
    ac: 15,
    hp: 7,
    hitDice: "2d6",
    speed: { walk: 30 },
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    savingThrows: {},
    skills: { stealth: 6 },
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 9",
    languages: "Common, Goblin",
    cr: "1/4",
    xp: 50,
    traits: [
      { name: "Nimble Escape", description: "Can take the Disengage or Hide action as a bonus action each turn." },
    ],
    actions: [
      { name: "Scimitar", description: "Melee attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) slashing damage." },
      { name: "Shortbow", description: "Ranged attack: +4 to hit, range 80/320 ft. Hit: 5 (1d6+2) piercing damage." },
    ],
  },
  {
    id: "wolf",
    name: "Wolf",
    size: "Medium",
    type: "Beast",
    alignment: "Unaligned",
    ac: 13,
    hp: 11,
    hitDice: "2d8+2",
    speed: { walk: 40 },
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    savingThrows: {},
    skills: { perception: 3, stealth: 4 },
    resistances: [],
    immunities: [],
    senses: "passive Perception 13",
    languages: "—",
    cr: "1/4",
    xp: 50,
    traits: [
      { name: "Keen Hearing and Smell", description: "Advantage on Wisdom (Perception) checks that rely on hearing or smell." },
      { name: "Pack Tactics", description: "Advantage on attack rolls against a creature if at least one ally is within 5 feet of it and not incapacitated." },
    ],
    actions: [
      { name: "Bite", description: "Melee attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) piercing damage; target must succeed a DC 11 Strength save or be knocked prone." },
    ],
  },
  {
    id: "skeleton",
    name: "Skeleton",
    size: "Medium",
    type: "Undead",
    alignment: "Lawful Evil",
    ac: 13,
    hp: 13,
    hitDice: "2d8+4",
    speed: { walk: 30 },
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: ["poison"],
    senses: "Darkvision 60 ft., passive Perception 9",
    languages: "understands languages known in life but can't speak",
    cr: "1/4",
    xp: 50,
    traits: [],
    actions: [
      { name: "Shortsword", description: "Melee attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage." },
      { name: "Shortbow", description: "Ranged attack: +4 to hit, range 80/320 ft. Hit: 5 (1d6+2) piercing damage." },
    ],
  },
  {
    id: "zombie",
    name: "Zombie",
    size: "Medium",
    type: "Undead",
    alignment: "Neutral Evil",
    ac: 8,
    hp: 22,
    hitDice: "3d8+9",
    speed: { walk: 20 },
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    savingThrows: { wis: 0 },
    skills: {},
    resistances: [],
    immunities: ["poison"],
    senses: "Darkvision 60 ft., passive Perception 8",
    languages: "understands languages known in life but can't speak",
    cr: "1/4",
    xp: 50,
    traits: [
      { name: "Undead Fortitude", description: "If damage would reduce it to 0 HP, it makes a Constitution save (DC 5 + damage taken) to drop to 1 HP instead, unless the damage is radiant or a critical hit." },
    ],
    actions: [
      { name: "Slam", description: "Melee attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) bludgeoning damage." },
    ],
  },
  {
    id: "bandit",
    name: "Bandit",
    size: "Medium",
    type: "Humanoid",
    alignment: "Any Non-Lawful",
    ac: 12,
    hp: 11,
    hitDice: "2d8+2",
    speed: { walk: 30 },
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: [],
    senses: "passive Perception 10",
    languages: "any one language (usually Common)",
    cr: "1/8",
    xp: 25,
    traits: [],
    actions: [
      { name: "Scimitar", description: "Melee attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) slashing damage." },
      { name: "Light Crossbow", description: "Ranged attack: +3 to hit, range 80/320 ft. Hit: 5 (1d8+1) piercing damage." },
    ],
  },
  {
    id: "giant_rat",
    name: "Giant Rat",
    size: "Small",
    type: "Beast",
    alignment: "Unaligned",
    ac: 12,
    hp: 7,
    hitDice: "2d6",
    speed: { walk: 30 },
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 10",
    languages: "—",
    cr: "1/8",
    xp: 25,
    traits: [
      { name: "Pack Tactics", description: "Advantage on attack rolls against a creature if at least one ally is within 5 feet of it and not incapacitated." },
    ],
    actions: [
      { name: "Bite", description: "Melee attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4+2) piercing damage." },
    ],
  },
  {
    id: "kobold",
    name: "Kobold",
    size: "Small",
    type: "Dragon",
    alignment: "Lawful Evil",
    ac: 12,
    hp: 5,
    hitDice: "2d6-2",
    speed: { walk: 30 },
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    savingThrows: {},
    skills: { stealth: 4 },
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 8",
    languages: "Common, Draconic",
    cr: "1/8",
    xp: 25,
    traits: [
      { name: "Pack Tactics", description: "Advantage on attack rolls against a creature if at least one ally is within 5 feet of it and not incapacitated." },
      { name: "Sunlight Sensitivity", description: "Disadvantage on attack rolls and Wisdom (Perception) checks that rely on sight while in sunlight." },
    ],
    actions: [
      { name: "Dagger", description: "Melee or ranged attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4+2) piercing damage." },
    ],
  },
  {
    id: "orc_warrior",
    name: "Orc",
    size: "Medium",
    type: "Humanoid",
    alignment: "Chaotic Evil",
    ac: 13,
    hp: 15,
    hitDice: "2d8+6",
    speed: { walk: 30 },
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    savingThrows: {},
    skills: { intimidation: 2 },
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 10",
    languages: "Common, Orc",
    cr: "1/2",
    xp: 100,
    traits: [
      { name: "Aggressive", description: "As a bonus action, can move up to its speed toward a hostile creature it can see." },
    ],
    actions: [
      { name: "Greataxe", description: "Melee attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12+3) slashing damage." },
      { name: "Javelin", description: "Melee or ranged attack: +5 to hit, reach 5 ft. or range 30/120 ft. Hit: 6 (1d6+3) piercing damage." },
    ],
  },
  {
    id: "giant_spider",
    name: "Giant Spider",
    size: "Large",
    type: "Beast",
    alignment: "Unaligned",
    ac: 14,
    hp: 26,
    hitDice: "4d10+4",
    speed: { walk: 30, climb: 30 },
    abilities: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    savingThrows: {},
    skills: { stealth: 7 },
    resistances: [],
    immunities: [],
    senses: "Blindsight 10 ft., darkvision 60 ft., passive Perception 10",
    languages: "—",
    cr: "1",
    xp: 200,
    traits: [
      { name: "Spider Climb", description: "Can climb difficult surfaces, including upside down on ceilings, without needing to make a check." },
      { name: "Web Sense", description: "While in contact with a web, knows the location of any other creature in contact with the same web." },
    ],
    actions: [
      { name: "Bite", description: "Melee attack: +5 to hit, reach 5 ft., one creature. Hit: 7 (1d8+3) piercing damage plus 9 (2d8) poison damage on a failed DC 11 Constitution save." },
      { name: "Web", description: "Ranged attack (recharge 5-6): +5 to hit, range 30/60 ft. A target is restrained by webbing (AC 10, 5 HP) until it breaks free." },
    ],
  },
  {
    id: "owlbear",
    name: "Owlbear",
    size: "Large",
    type: "Monstrosity",
    alignment: "Unaligned",
    ac: 13,
    hp: 59,
    hitDice: "7d10+21",
    speed: { walk: 40 },
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    savingThrows: {},
    skills: { perception: 3 },
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 13",
    languages: "—",
    cr: "3",
    xp: 700,
    traits: [
      { name: "Keen Sight and Smell", description: "Advantage on Wisdom (Perception) checks that rely on sight or smell." },
    ],
    actions: [
      { name: "Multiattack", description: "Makes one beak attack and one claws attack." },
      { name: "Beak", description: "Melee attack: +7 to hit, reach 5 ft., one target. Hit: 10 (1d10+5) piercing damage." },
      { name: "Claws", description: "Melee attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8+5) slashing damage." },
    ],
  },
  {
    id: "ogre",
    name: "Ogre",
    size: "Large",
    type: "Giant",
    alignment: "Chaotic Evil",
    ac: 11,
    hp: 59,
    hitDice: "7d10+21",
    speed: { walk: 40 },
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 8",
    languages: "Common, Giant",
    cr: "2",
    xp: 450,
    traits: [],
    actions: [
      { name: "Greatclub", description: "Melee attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8+4) bludgeoning damage." },
      { name: "Javelin", description: "Melee or ranged attack: +6 to hit, reach 5 ft. or range 30/120 ft. Hit: 11 (2d6+4) piercing damage." },
    ],
  },
  {
    id: "ghoul",
    name: "Ghoul",
    size: "Medium",
    type: "Undead",
    alignment: "Chaotic Evil",
    ac: 12,
    hp: 22,
    hitDice: "5d8",
    speed: { walk: 30 },
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: ["poison"],
    senses: "Darkvision 60 ft., passive Perception 10",
    languages: "Common",
    cr: "1",
    xp: 200,
    traits: [],
    actions: [
      { name: "Bite", description: "Melee attack: +2 to hit, reach 5 ft., one target. Hit: 5 (2d4) piercing damage." },
      { name: "Claws", description: "Melee attack: +4 to hit, reach 5 ft., one target (not undead). Hit: 6 (2d4+2) slashing damage; target paralyzed for 1 minute on a failed DC 10 Constitution save." },
    ],
  },
  {
    id: "giant_centipede",
    name: "Giant Centipede",
    size: "Small",
    type: "Beast",
    alignment: "Unaligned",
    ac: 13,
    hp: 4,
    hitDice: "1d6+1",
    speed: { walk: 30, climb: 30 },
    abilities: { str: 5, dex: 14, con: 12, int: 1, wis: 7, cha: 3 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: [],
    senses: "Blindsight 30 ft., passive Perception 8",
    languages: "—",
    cr: "1/4",
    xp: 50,
    traits: [],
    actions: [
      { name: "Bite", description: "Melee attack: +4 to hit, reach 5 ft., one creature. Hit: 4 (1d4+2) piercing damage plus poison damage on a failed DC 11 Constitution save; poisoned 1 hour on a failed save." },
    ],
  },
  {
    id: "stirge",
    name: "Stirge",
    size: "Tiny",
    type: "Beast",
    alignment: "Unaligned",
    ac: 14,
    hp: 2,
    hitDice: "1d4",
    speed: { walk: 10, fly: 40 },
    abilities: { str: 4, dex: 16, con: 11, int: 2, wis: 8, cha: 6 },
    savingThrows: {},
    skills: {},
    resistances: [],
    immunities: [],
    senses: "Darkvision 60 ft., passive Perception 9",
    languages: "—",
    cr: "1/8",
    xp: 25,
    traits: [],
    actions: [
      { name: "Blood Drain", description: "Melee attack: +5 to hit, reach 5 ft., one creature. Hit: 5 (1d4+3) piercing damage, and the stirge attaches, draining 4 (1d4+2) HP at the start of each of its turns until removed." },
    ],
  },
  {
    id: "black_bear",
    name: "Black Bear",
    size: "Medium",
    type: "Beast",
    alignment: "Unaligned",
    ac: 11,
    hp: 19,
    hitDice: "3d8+6",
    speed: { walk: 40, climb: 30 },
    abilities: { str: 15, dex: 10, con: 14, int: 2, wis: 12, cha: 7 },
    savingThrows: {},
    skills: { perception: 3 },
    resistances: [],
    immunities: [],
    senses: "passive Perception 13",
    languages: "—",
    cr: "1/2",
    xp: 100,
    traits: [
      { name: "Keen Smell", description: "Advantage on Wisdom (Perception) checks that rely on smell." },
    ],
    actions: [
      { name: "Multiattack", description: "Makes one bite attack and one claws attack." },
      { name: "Bite", description: "Melee attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d6+2) piercing damage." },
      { name: "Claws", description: "Melee attack: +3 to hit, reach 5 ft., one target. Hit: 7 (2d4+2) slashing damage." },
    ],
  },
];

export const MONSTER_BY_ID: Record<string, Monster> = Object.fromEntries(
  MONSTERS.map((m) => [m.id, m]),
);
