import type { Spell } from "@/lib/rules/types";

function spell(
  id: string,
  name: string,
  level: number,
  school: string,
  castingTime: string,
  range: string,
  components: { v: boolean; s: boolean; m: string | null },
  duration: string,
  concentration: boolean,
  ritual: boolean,
  classes: string[],
  description: string,
): Spell {
  return { id, name, level, school, castingTime, range, components, duration, concentration, ritual, classes, description };
}

const V = { v: true, s: false, m: null };
const VS = { v: true, s: true, m: null };
const S = { v: false, s: true, m: null };

export const SPELLS: Spell[] = [
  // ---- Cantrips ----
  spell("acid_splash", "Acid Splash", 0, "Conjuration", "1 action", "60 feet", V, "Instantaneous", false, false, ["sorcerer", "wizard"], "Hurl a bubble of acid at one or two creatures within 5 feet of each other, dealing acid damage on a failed Dexterity save."),
  spell("chill_touch", "Chill Touch", 0, "Necromancy", "1 action", "120 feet", VS, "1 round", false, false, ["sorcerer", "warlock", "wizard"], "A ghostly skeletal hand strikes a creature, dealing necrotic damage and preventing it from regaining hit points until your next turn."),
  spell("dancing_lights", "Dancing Lights", 0, "Illusion", "1 action", "120 feet", VS, "Concentration, up to 1 minute", true, false, ["bard", "sorcerer", "wizard"], "Create up to four torch-sized lights that you can move around within range."),
  spell("fire_bolt", "Fire Bolt", 0, "Evocation", "1 action", "120 feet", V, "Instantaneous", false, false, ["sorcerer", "wizard"], "Hurl a mote of fire at a creature or object, dealing fire damage on a hit."),
  spell("guidance", "Guidance", 0, "Divination", "1 action", "Touch", VS, "Concentration, up to 1 minute", true, false, ["cleric", "druid"], "Touch a willing creature; once before the spell ends, it can add 1d4 to one ability check."),
  spell("light", "Light", 0, "Evocation", "1 action", "Touch", { v: true, s: false, m: "a firefly or phosphorescent moss" }, "1 hour", false, false, ["bard", "cleric", "sorcerer", "wizard"], "An object you touch sheds bright light in a 20-foot radius."),
  spell("mage_hand", "Mage Hand", 0, "Conjuration", "1 action", "30 feet", VS, "1 minute", false, false, ["bard", "sorcerer", "warlock", "wizard"], "Create a spectral hand that can manipulate objects, open doors, and carry up to 10 pounds."),
  spell("mending", "Mending", 0, "Transmutation", "1 minute", "Touch", { v: true, s: true, m: "two lodestones" }, "Instantaneous", false, false, ["bard", "cleric", "druid", "sorcerer", "wizard"], "Repairs a single break or tear in an object you touch."),
  spell("minor_illusion", "Minor Illusion", 0, "Illusion", "1 action", "30 feet", { v: false, s: true, m: "a bit of fleece" }, "1 minute", false, false, ["bard", "sorcerer", "warlock", "wizard"], "Create a sound or an image of an object within range that lasts for the duration."),
  spell("poison_spray", "Poison Spray", 0, "Conjuration", "1 action", "10 feet", V, "Instantaneous", false, false, ["druid", "sorcerer", "warlock", "wizard"], "Project a puff of noxious gas at a creature, dealing poison damage on a failed Constitution save."),
  spell("prestidigitation", "Prestidigitation", 0, "Transmutation", "1 action", "10 feet", VS, "Up to 1 hour", false, false, ["bard", "sorcerer", "warlock", "wizard"], "A minor magical trick: create a harmless sensory effect, light or snuff a small flame, clean or soil an object, or similar."),
  spell("produce_flame", "Produce Flame", 0, "Conjuration", "1 action", "Self", VS, "10 minutes", false, false, ["druid"], "A flickering flame appears in your hand, shedding light and usable as a thrown attack dealing fire damage."),
  spell("ray_of_frost", "Ray of Frost", 0, "Evocation", "1 action", "60 feet", V, "Instantaneous", false, false, ["sorcerer", "wizard"], "A beam of frost streaks toward a creature, dealing cold damage and reducing its speed by 10 feet until your next turn."),
  spell("sacred_flame", "Sacred Flame", 0, "Evocation", "1 action", "60 feet", V, "Instantaneous", false, false, ["cleric"], "Flame-like radiance descends on a creature that must succeed a Dexterity save or take radiant damage."),
  spell("shillelagh", "Shillelagh", 0, "Transmutation", "Bonus Action", "Touch", { v: false, s: true, m: "mistletoe, a shamrock leaf, and a club or quarterstaff" }, "1 minute", false, false, ["druid"], "Imbue a club or quarterstaff with nature's power; use Wisdom for its attack and damage rolls, and its damage die becomes a d8."),
  spell("shocking_grasp", "Shocking Grasp", 0, "Evocation", "1 action", "Touch", VS, "Instantaneous", false, false, ["sorcerer", "wizard"], "Lightning springs from your hand into a creature you touch, dealing lightning damage; advantage if the target is wearing metal armor."),
  spell("spare_the_dying", "Spare the Dying", 0, "Necromancy", "1 action", "Touch", V, "Instantaneous", false, false, ["cleric"], "Touch a creature with 0 hit points; it becomes stable."),
  spell("thaumaturgy", "Thaumaturgy", 0, "Divination", "1 action", "30 feet", V, "Up to 1 minute", false, false, ["cleric"], "Manifest a minor wonder: your voice booms, harmless tremors, doors swing, eyes flicker, and similar effects."),
  spell("thorn_whip", "Thorn Whip", 0, "Transmutation", "1 action", "30 feet", { v: false, s: true, m: "the stem of a plant with thorns" }, "Instantaneous", false, false, ["druid", "sorcerer"], "A vine-like whip strikes a creature, dealing piercing damage and pulling it up to 10 feet closer to you."),
  spell("true_strike", "True Strike", 0, "Divination", "1 action", "Self", S, "Instantaneous", false, false, ["bard", "sorcerer", "warlock", "wizard"], "Guide a melee weapon strike this turn using your spellcasting ability instead of Strength or Dexterity."),
  spell("vicious_mockery", "Vicious Mockery", 0, "Enchantment", "1 action", "60 feet", V, "Instantaneous", false, false, ["bard"], "Unleash an insult laced with subtle magic at a creature, dealing psychic damage and imposing disadvantage on its next attack roll if it fails a Wisdom save."),
  spell("eldritch_blast", "Eldritch Blast", 0, "Evocation", "1 action", "120 feet", VS, "Instantaneous", false, false, ["warlock"], "A beam of crackling energy strikes a creature, dealing force damage; creates an additional beam at higher character levels."),
  spell("druidcraft", "Druidcraft", 0, "Transmutation", "1 action", "30 feet", VS, "Instantaneous", false, false, ["druid"], "Create a minor, harmless nature-themed effect: predict the weather, make a flower bloom, or a similar sensory trick."),

  // ---- 1st level ----
  spell("burning_hands", "Burning Hands", 1, "Evocation", "1 action", "Self (15-foot cone)", VS, "Instantaneous", false, false, ["sorcerer", "wizard"], "A thin sheet of flame shoots from your hands, dealing fire damage to each creature in a 15-foot cone."),
  spell("magic_missile", "Magic Missile", 1, "Evocation", "1 action", "120 feet", VS, "Instantaneous", false, false, ["sorcerer", "wizard"], "Create three glowing darts of magical force; each unerringly strikes a creature of your choice, dealing force damage."),
  spell("shield", "Shield", 1, "Abjuration", "Reaction", "Self", VS, "1 round", false, false, ["sorcerer", "wizard"], "An invisible barrier grants +5 AC until the start of your next turn, including against the triggering attack, and blocks Magic Missile."),
  spell("mage_armor", "Mage Armor", 1, "Abjuration", "1 action", "Touch", { v: false, s: true, m: "a piece of cured leather" }, "8 hours", false, false, ["sorcerer", "wizard"], "A protective magical force covers a willing creature, setting its base AC to 13 + Dexterity modifier."),
  spell("chromatic_orb", "Chromatic Orb", 1, "Evocation", "1 action", "90 feet", { v: true, s: true, m: "a diamond worth at least 50 gp" }, "Instantaneous", false, false, ["sorcerer", "wizard"], "Hurl a 4-inch orb of energy of a damage type you choose, dealing damage on a hit."),
  spell("find_familiar", "Find Familiar", 1, "Conjuration", "1 hour", "10 feet", { v: false, s: true, m: "burning incense worth 10 gp" }, "Instantaneous", false, true, ["warlock", "wizard"], "Gain the service of a spirit that takes the form of a small animal, which can deliver touch spells and scout for you."),
  spell("grease", "Grease", 1, "Conjuration", "1 action", "60 feet", { v: false, s: true, m: "a bit of pork rind or butter" }, "1 minute", false, false, ["wizard"], "Cover the ground in a 10-foot square with slick grease, forcing Dexterity saves or creatures fall prone."),
  spell("charm_person", "Charm Person", 1, "Enchantment", "1 action", "30 feet", VS, "1 hour", false, false, ["bard", "druid", "sorcerer", "warlock", "wizard"], "A humanoid you can see must succeed a Wisdom save or be charmed by you for the duration."),
  spell("comprehend_languages", "Comprehend Languages", 1, "Divination", "1 action", "Self", { v: true, s: true, m: "a pinch of soot and salt" }, "1 hour", false, true, ["bard", "warlock", "wizard"], "You understand the literal meaning of any spoken language and can read any written language for the duration."),
  spell("detect_magic", "Detect Magic", 1, "Divination", "1 action", "Self", VS, "Concentration, up to 10 minutes", true, true, ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"], "Sense the presence of magic within 30 feet and, with your action, see a faint aura around a visible magical item or creature."),
  spell("disguise_self", "Disguise Self", 1, "Illusion", "1 action", "Self", VS, "1 hour", false, false, ["bard", "sorcerer", "wizard"], "Change your appearance, including clothing and gear, until the spell ends or you use an action to end it."),
  spell("expeditious_retreat", "Expeditious Retreat", 1, "Transmutation", "Bonus Action", "Self", VS, "Concentration, up to 10 minutes", true, false, ["sorcerer", "warlock", "wizard"], "Gain the ability to Dash as a bonus action for the duration."),
  spell("faerie_fire", "Faerie Fire", 1, "Evocation", "1 action", "60 feet", V, "Concentration, up to 1 minute", true, false, ["bard", "druid"], "Objects in a 20-foot cube are outlined in light; affected creatures can't benefit from being invisible, and attacks against them have advantage."),
  spell("feather_fall", "Feather Fall", 1, "Transmutation", "Reaction", "60 feet", { v: true, s: false, m: "a small feather" }, "1 minute", false, false, ["bard", "sorcerer", "wizard"], "Choose up to five falling creatures; their rate of descent slows to 60 feet per round and they take no fall damage."),
  spell("fog_cloud", "Fog Cloud", 1, "Conjuration", "1 action", "120 feet", V, "Concentration, up to 1 hour", true, false, ["druid", "ranger", "sorcerer", "wizard"], "Create a 20-foot-radius sphere of fog that heavily obscures its area."),
  spell("identify", "Identify", 1, "Divination", "1 minute", "Touch", { v: true, s: true, m: "a pearl worth at least 100 gp" }, "Instantaneous", false, true, ["bard", "wizard"], "Learn the properties, including how to use, a touched magic item or similar object."),
  spell("jump", "Jump", 1, "Transmutation", "1 action", "Touch", { v: false, s: true, m: "a grasshopper's hind leg" }, "1 minute", false, false, ["druid", "ranger", "sorcerer", "wizard"], "A creature's jump distance is tripled until the spell ends."),
  spell("longstrider", "Longstrider", 1, "Transmutation", "1 action", "Touch", { v: false, s: true, m: "a pinch of dirt" }, "1 hour", false, false, ["bard", "druid", "ranger", "wizard"], "A creature's speed increases by 10 feet for the duration."),
  spell("protection_from_evil_and_good", "Protection from Evil and Good", 1, "Abjuration", "1 action", "Touch", { v: true, s: true, m: "holy water or powdered silver and iron" }, "Concentration, up to 10 minutes", true, false, ["cleric", "paladin", "sorcerer", "warlock", "wizard"], "A willing creature gains protection from aberrations, celestials, elementals, fey, fiends, and undead: disadvantage against them, and no charm/frighten/possession from them."),
  spell("silent_image", "Silent Image", 1, "Illusion", "1 action", "60 feet", { v: false, s: true, m: "a bit of fleece" }, "Concentration, up to 10 minutes", true, false, ["bard", "sorcerer", "wizard"], "Create a purely visual illusion of an object, creature, or phenomenon within a 15-foot cube."),
  spell("sleep", "Sleep", 1, "Enchantment", "1 action", "90 feet", { v: true, s: true, m: "a pinch of sand" }, "1 minute", false, false, ["bard", "sorcerer", "wizard"], "Creatures in a 20-foot radius fall unconscious, weakest hit points first, up to a total of 5d8 hit points affected."),
  spell("tashas_hideous_laughter", "Tasha's Hideous Laughter", 1, "Enchantment", "1 action", "30 feet", { v: true, s: true, m: "tiny tarts and a feather" }, "Concentration, up to 1 minute", true, false, ["bard", "wizard"], "A creature that fails a Wisdom save falls prone, incapacitated with laughter for the duration."),
  spell("thunderwave", "Thunderwave", 1, "Evocation", "1 action", "Self (15-foot cube)", VS, "Instantaneous", false, false, ["bard", "druid", "sorcerer", "wizard"], "A wave of thunderous force sweeps out from you, damaging and pushing creatures in a 15-foot cube."),
  spell("witch_bolt", "Witch Bolt", 1, "Evocation", "1 action", "30 feet", { v: true, s: true, m: "a twig from a tree struck by lightning" }, "Concentration, up to 1 minute", true, false, ["sorcerer", "warlock", "wizard"], "A lasting arc of electricity strikes a creature, dealing damage again each turn you maintain concentration."),
  spell("unseen_servant", "Unseen Servant", 1, "Conjuration", "1 action", "60 feet", { v: true, s: true, m: "a bit of string and wood" }, "1 hour", false, true, ["bard", "warlock", "wizard"], "Create an invisible, mindless force that can perform simple tasks like fetching, cleaning, and opening doors."),
  spell("hex", "Hex", 1, "Enchantment", "Bonus Action", "90 feet", { v: false, s: true, m: "a petrified eye of a newt" }, "Concentration, up to 1 hour", true, false, ["warlock"], "Curse a creature: deal extra necrotic damage with your attacks against it and impose disadvantage on one chosen ability."),
  spell("arms_of_hadar", "Arms of Hadar", 1, "Conjuration", "1 action", "Self (10-foot radius)", VS, "Instantaneous", false, false, ["warlock"], "Tendrils of dark energy erupt around you, damaging nearby creatures and preventing Reactions until your next turn."),
  spell("hellish_rebuke", "Hellish Rebuke", 1, "Evocation", "Reaction", "60 feet", VS, "Instantaneous", false, false, ["warlock"], "In response to being damaged, point at the attacker and wreathe it in hellish flames dealing fire damage on a failed save."),
  spell("bless", "Bless", 1, "Enchantment", "1 action", "30 feet", { v: true, s: true, m: "a sprinkling of holy water" }, "Concentration, up to 1 minute", true, false, ["cleric", "paladin"], "Up to three creatures you choose add 1d4 to attack rolls and saving throws for the duration."),
  spell("command", "Command", 1, "Enchantment", "1 action", "60 feet", V, "1 round", false, false, ["cleric", "paladin"], "Speak a one-word command to a creature; it must obey on its next turn if it fails a Wisdom save."),
  spell("create_or_destroy_water", "Create or Destroy Water", 1, "Transmutation", "1 action", "30 feet", { v: true, s: true, m: "a drop of water if creating, or a few grains of sand if destroying" }, "Instantaneous", false, false, ["cleric", "druid"], "Create up to 10 gallons of clean water, or destroy up to 10 gallons of water in an open container."),
  spell("cure_wounds", "Cure Wounds", 1, "Abjuration", "1 action", "Touch", VS, "Instantaneous", false, false, ["bard", "cleric", "druid", "paladin", "ranger"], "A creature you touch regains hit points equal to 1d8 plus your spellcasting ability modifier."),
  spell("detect_evil_and_good", "Detect Evil and Good", 1, "Divination", "1 action", "Self", VS, "Concentration, up to 10 minutes", true, false, ["cleric", "paladin"], "Sense the presence and general direction of celestials, fiends, undead, and hallowed or desecrated ground within 30 feet."),
  spell("guiding_bolt", "Guiding Bolt", 1, "Evocation", "1 action", "120 feet", VS, "1 round", false, false, ["cleric"], "A flash of light streaks toward a creature, dealing radiant damage; the next attack against it before your next turn has advantage."),
  spell("healing_word", "Healing Word", 1, "Abjuration", "Bonus Action", "60 feet", V, "Instantaneous", false, false, ["bard", "cleric", "druid"], "A creature of your choice regains hit points equal to 1d4 plus your spellcasting ability modifier."),
  spell("inflict_wounds", "Inflict Wounds", 1, "Necromancy", "1 action", "Touch", VS, "Instantaneous", false, false, ["cleric"], "Make a melee spell attack against a creature you can reach, dealing necrotic damage on a hit."),
  spell("sanctuary", "Sanctuary", 1, "Abjuration", "Bonus Action", "30 feet", { v: true, s: true, m: "a small silver mirror" }, "1 minute", false, false, ["cleric"], "Ward a creature so attackers must make a Wisdom save or choose a different target."),
  spell("shield_of_faith", "Shield of Faith", 1, "Abjuration", "Bonus Action", "60 feet", { v: true, s: true, m: "a small parchment with a bit of holy text" }, "Concentration, up to 10 minutes", true, false, ["cleric", "paladin"], "A shimmering field grants a creature +2 AC for the duration."),
  spell("animal_friendship", "Animal Friendship", 1, "Enchantment", "1 action", "30 feet", { v: true, s: true, m: "a morsel of food" }, "24 hours", false, false, ["bard", "druid", "ranger"], "A beast you target must succeed a Wisdom save or regard you as a friend for the duration."),
  spell("entangle", "Entangle", 1, "Conjuration", "1 action", "90 feet", V, "Concentration, up to 1 minute", true, false, ["druid"], "Grasping weeds and vines sprout in a 20-foot square, restraining creatures that fail a Strength save."),
  spell("goodberry", "Goodberry", 1, "Transmutation", "1 action", "Touch", VS, "Instantaneous", false, false, ["druid", "ranger"], "Up to ten berries appear, each providing 1 hit point when eaten and enough nourishment to sustain a creature for a day."),
  spell("speak_with_animals", "Speak with Animals", 1, "Divination", "1 action", "Self", VS, "10 minutes", false, true, ["bard", "druid", "ranger"], "Gain the ability to comprehend and verbally communicate with beasts for the duration."),
  spell("dissonant_whispers", "Dissonant Whispers", 1, "Enchantment", "1 action", "60 feet", V, "Instantaneous", false, false, ["bard"], "Whisper a discordant melody only one creature can hear, dealing psychic damage and causing it to flee on a failed save."),
  spell("heroism", "Heroism", 1, "Enchantment", "1 action", "Touch", VS, "Concentration, up to 1 minute", true, false, ["bard", "paladin"], "A willing creature is imbued with bravery, gaining temporary hit points and immunity to being frightened."),
  spell("bane", "Bane", 1, "Enchantment", "1 action", "30 feet", { v: true, s: true, m: "a drop of blood" }, "Concentration, up to 1 minute", true, false, ["bard", "cleric"], "Up to three creatures must subtract 1d4 from attack rolls and saving throws for the duration."),
  spell("hunters_mark", "Hunter's Mark", 1, "Divination", "Bonus Action", "90 feet", V, "Concentration, up to 1 hour", true, false, ["ranger"], "Mark a creature as your quarry; your weapon attacks against it deal an extra 1d6 damage and you have advantage on tracking it."),
  spell("ensnaring_strike", "Ensnaring Strike", 1, "Conjuration", "Bonus Action", "Self", V, "Concentration, up to 1 minute", true, false, ["ranger"], "The next time you hit a creature with a weapon attack before this spell ends, grasping vines restrain it on a failed Strength save."),
  spell("alarm", "Alarm", 1, "Abjuration", "1 minute", "30 feet", { v: true, s: true, m: "a tiny bell and a piece of fine silver wire" }, "8 hours", false, true, ["ranger", "wizard"], "Set an audible or mental alarm against unwanted intrusion into an area."),
  spell("divine_favor", "Divine Favor", 1, "Enchantment", "Bonus Action", "Self", VS, "Concentration, up to 1 minute", true, false, ["paladin"], "Your weapon attacks deal an extra 1d4 radiant damage on a hit for the duration."),
  spell("searing_smite", "Searing Smite", 1, "Evocation", "Bonus Action", "Self", V, "Concentration, up to 1 minute", true, false, ["paladin"], "The next time you hit with a melee weapon attack, the weapon flares with fire, dealing extra fire damage and igniting the target."),
];

export const SPELL_BY_ID: Record<string, Spell> = Object.fromEntries(
  SPELLS.map((s) => [s.id, s]),
);
